version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install aws-sam-cli
      

  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build

  build:
    commands:
      - echo "Running out build commands..."