version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install aws-sam-cli
      - cd aws-juan

  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build

  build:
    commands:
      - echo "Running out build commands..."
      - sam package --output-template-file packaged.yaml --s3-bucket andres-ocampo-test-bucket

  artifacts:
    files:
    - packaged.yaml
    